server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dosyahub
  
  # PostgreSQL Veritabanı Yapılandırması
  datasource:
    url: jdbc:postgresql://localhost:5432/dosyahub
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Yapılandırması
  jpa:
    hibernate:
      ddl-auto: update  # Veritabanı şemasını otomatik oluştur
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Dosya Yükleme Yapılandırması
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB
  
  # CORS Yapılandırması
  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
      allowed-headers: "*"
      exposed-headers: Content-Disposition,Content-Type,Content-Length,Authorization
      allow-credentials: true
      max-age: 3600

# Dosya Depolama Tipi Yapılandırması
storage:
  type: minio  # minio veya filesystem
  upload-dir: uploads

# MinIO Yapılandırması
minio:
  endpoint: http://localhost:9000
  port: 9000
  access-key: minioadmin
  secret-key: minioadmin
  secure: false
  bucket-name: dosyahub
  enabled: true  # MinIO etkinleştirildi

# JWT Yapılandırması
jwt:
  secret: ${JWT_SECRET:5A7134743777217A25432A462D4A614E645267556B58703272357538782F413F}
  expiration: 86400000  # 24 saat (milisaniye)
  issuer: dosyahub

# SpringDoc OpenAPI Yapılandırması
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.dosyahub.controller
  pathsToMatch: /**
  show-actuator: true

# Actuator Yapılandırması
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Loglama Yapılandırması
logging:
  level:
    root: INFO
    com.dosyahub: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    org.springdoc: DEBUG 